-- MySQL Script generated by MySQL Workbench
-- Tue May 16 23:38:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alexandrktbotbot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alexandrktbotbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alexandrktbotbot` DEFAULT CHARACTER SET utf8 ;
USE `alexandrktbotbot` ;

-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`User` (
  `email` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(25) NULL,
  `prenom` VARCHAR(45) NULL,
  `section` VARCHAR(25) NULL,
  `password` VARCHAR(255) NULL,
  `seed` VARCHAR(255) NULL,
  `annee` INT NULL,
  `statut` INT NULL,
  `parrain` VARCHAR(255) NULL,
  `phone` VARCHAR(10) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`StatutAnnonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`StatutAnnonce` (
  `idstatutAnnonce` INT NOT NULL AUTO_INCREMENT,
  `libelleStatutAnnonce` VARCHAR(255) NULL,
  PRIMARY KEY (`idstatutAnnonce`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Covoiturage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Covoiturage` (
  `adresseDepartCovoiturage` VARCHAR(255) NULL,
  `prixTrajetCovoiturage` DOUBLE NULL,
  `heureCovoiturage` DATETIME NULL,
  `adresseArriveCovoiturage` VARCHAR(255) NULL,
  `nbPlaceDisponibleCovoiturage` INT NULL,
  `bagageCovoiturage` VARCHAR(255) NULL,
  `idCovoiturage` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCovoiturage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Appartement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Appartement` (
  `loyerAppartement` INT NULL,
  `dateCessionAppartement` DATETIME NULL,
  `adresseAppartement` VARCHAR(255) NULL,
  `nbPieceAppartement` INT NULL,
  `surfaceAppartement` INT NULL,
  `photoAppartement` VARCHAR(255) NULL,
  `IdAppartement` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdAppartement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Troc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Troc` (
  `prixTroc` DOUBLE NULL,
  `dateTroc` DATETIME NULL,
  `adresseRecupTroc` VARCHAR(255) NULL,
  `photoTroc` VARCHAR(255) NULL,
  `IdTroc` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdTroc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `libelleVille` VARCHAR(255) NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Annonce` (
  `idAnnonce` INT NOT NULL AUTO_INCREMENT,
  `messageAnnonce` TEXT(1000) NULL,
  `titreAnnonce` VARCHAR(255) NULL,
  `dateAjoutAnnoncecol` DATETIME NULL,
  `StatutAnnonce_idstatutAnnonce` INT NOT NULL,
  `Covoiturage_idCovoiturage` INT NOT NULL,
  `Appartement_IdAppartement` INT NOT NULL,
  `Troc_IdCovoiturage` INT NOT NULL,
  `Ville_idVille` INT NOT NULL,
  `User_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAnnonce`, `StatutAnnonce_idstatutAnnonce`, `Covoiturage_idCovoiturage`, `Appartement_IdAppartement`, `Troc_IdCovoiturage`, `Ville_idVille`, `User_email`),
  INDEX `fk_Annonce_StatutAnnonce1_idx` (`StatutAnnonce_idstatutAnnonce` ASC),
  INDEX `fk_Annonce_Covoiturage1_idx` (`Covoiturage_idCovoiturage` ASC),
  INDEX `fk_Annonce_Appartement1_idx` (`Appartement_IdAppartement` ASC),
  INDEX `fk_Annonce_Troc1_idx` (`Troc_IdCovoiturage` ASC),
  INDEX `fk_Annonce_Ville1_idx` (`Ville_idVille` ASC),
  INDEX `fk_Annonce_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_Annonce_StatutAnnonce1`
    FOREIGN KEY (`StatutAnnonce_idstatutAnnonce`)
    REFERENCES `alexandrktbotbot`.`StatutAnnonce` (`idstatutAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Covoiturage1`
    FOREIGN KEY (`Covoiturage_idCovoiturage`)
    REFERENCES `alexandrktbotbot`.`Covoiturage` (`idCovoiturage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Appartement1`
    FOREIGN KEY (`Appartement_IdAppartement`)
    REFERENCES `alexandrktbotbot`.`Appartement` (`IdAppartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Troc1`
    FOREIGN KEY (`Troc_IdCovoiturage`)
    REFERENCES `alexandrktbotbot`.`Troc` (`IdTroc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Ville1`
    FOREIGN KEY (`Ville_idVille`)
    REFERENCES `alexandrktbotbot`.`Ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `alexandrktbotbot`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`StatutDemande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`StatutDemande` (
  `idStatutDemande` INT NOT NULL AUTO_INCREMENT,
  `libelleStatutDemande` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatutDemande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandrktbotbot`.`Demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alexandrktbotbot`.`Demande` (
  `idDemande` INT NOT NULL AUTO_INCREMENT,
  `messageDemande` TEXT(1000) NULL,
  `prixDemande` DOUBLE NULL,
  `dateDemande` DATETIME NULL,
  `Annonce_idAnnonce` INT NOT NULL,
  `StatutDemande_idStatutDemande` INT NOT NULL,
  `User_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDemande`, `Annonce_idAnnonce`, `StatutDemande_idStatutDemande`, `User_email`),
  INDEX `fk_Demande_Annonce1_idx` (`Annonce_idAnnonce` ASC),
  INDEX `fk_Demande_StatutDemande1_idx` (`StatutDemande_idStatutDemande` ASC),
  INDEX `fk_Demande_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_Demande_Annonce1`
    FOREIGN KEY (`Annonce_idAnnonce`)
    REFERENCES `alexandrktbotbot`.`Annonce` (`idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demande_StatutDemande1`
    FOREIGN KEY (`StatutDemande_idStatutDemande`)
    REFERENCES `alexandrktbotbot`.`StatutDemande` (`idStatutDemande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demande_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `alexandrktbotbot`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
