-- MySQL Script generated by MySQL Workbench
-- Tue May 16 23:21:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table  `User`
-- ----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `email` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(25) NULL,
  `prenom` VARCHAR(45) NULL,
  `section` VARCHAR(25) NULL,
  `password` VARCHAR(255) NULL,
  `seed` VARCHAR(255) NULL,
  `annee` INT NULL,
  `statut` INT NULL,
  `parrain` VARCHAR(255) NULL,
  `phone` VARCHAR(10) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `StatutAnnonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `StatutAnnonce` (
  `idstatutAnnonce` INT NOT NULL AUTO_INCREMENT,
  `libelleStatutAnnonce` VARCHAR(255) NULL,
  PRIMARY KEY (`idstatutAnnonce`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Covoiturage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Covoiturage` (
  `adresseDepartCovoiturage` VARCHAR(255) NULL,
  `prixTrajetCovoiturage` DOUBLE NULL,
  `heureCovoiturage` DATETIME NULL,
  `adresseArriveCovoiturage` VARCHAR(255) NULL,
  `nbPlaceDisponibleCovoiturage` INT NULL,
  `bagageCovoiturage` VARCHAR(255) NULL,
  `idCovoiturage` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCovoiturage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Appartement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Appartement` (
  `loyerAppartement` INT NULL,
  `dateCessionAppartement` DATETIME NULL,
  `adresseAppartement` VARCHAR(255) NULL,
  `nbPieceAppartement` INT NULL,
  `surfaceAppartement` INT NULL,
  `photoAppartement` VARCHAR(255) NULL,
  `IdAppartement` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdAppartement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Troc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Troc` (
  `prixTroc` DOUBLE NULL,
  `dateTroc` DATETIME NULL,
  `adresseRecupTroc` VARCHAR(255) NULL,
  `photoTroc` VARCHAR(255) NULL,
  `IdCovoiturage` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdCovoiturage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `libelleVille` VARCHAR(255) NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Annonce` (
  `idAnnonce` INT NOT NULL AUTO_INCREMENT,
  `messageAnnonce` TEXT(1000) NULL,
  `titreAnnonce` VARCHAR(255) NULL,
  `dateAjoutAnnoncecol` DATETIME NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `StatutAnnonce_idstatutAnnonce` INT NOT NULL,
  `Covoiturage_idCovoiturage` INT NOT NULL,
  `Appartement_IdAppartement` INT NOT NULL,
  `Troc_IdCovoiturage` INT NOT NULL,
  `Ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idAnnonce`, `Utilisateur_idUtilisateur`, `StatutAnnonce_idstatutAnnonce`, `Covoiturage_idCovoiturage`, `Appartement_IdAppartement`, `Troc_IdCovoiturage`, `Ville_idVille`),
  INDEX `fk_Annonce_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Annonce_StatutAnnonce1_idx` (`StatutAnnonce_idstatutAnnonce` ASC),
  INDEX `fk_Annonce_Covoiturage1_idx` (`Covoiturage_idCovoiturage` ASC),
  INDEX `fk_Annonce_Appartement1_idx` (`Appartement_IdAppartement` ASC),
  INDEX `fk_Annonce_Troc1_idx` (`Troc_IdCovoiturage` ASC),
  INDEX `fk_Annonce_Ville1_idx` (`Ville_idVille` ASC),
  CONSTRAINT `fk_Annonce_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES  `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_StatutAnnonce1`
    FOREIGN KEY (`StatutAnnonce_idstatutAnnonce`)
    REFERENCES  `StatutAnnonce` (`idstatutAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Covoiturage1`
    FOREIGN KEY (`Covoiturage_idCovoiturage`)
    REFERENCES  `Covoiturage` (`idCovoiturage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Appartement1`
    FOREIGN KEY (`Appartement_IdAppartement`)
    REFERENCES  `Appartement` (`IdAppartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Troc1`
    FOREIGN KEY (`Troc_IdCovoiturage`)
    REFERENCES  `Troc` (`IdCovoiturage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Ville1`
    FOREIGN KEY (`Ville_idVille`)
    REFERENCES  `Ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `StatutDemande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `StatutDemande` (
  `idStatutDemande` INT NOT NULL AUTO_INCREMENT,
  `libelleStatutDemande` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatutDemande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Demande` (
  `idDemande` INT NOT NULL AUTO_INCREMENT,
  `messageDemande` TEXT(1000) NULL,
  `prixDemande` DOUBLE NULL,
  `dateDemande` DATETIME NULL,
  `Annonce_idAnnonce` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `StatutDemande_idStatutDemande` INT NOT NULL,
  PRIMARY KEY (`idDemande`, `Annonce_idAnnonce`, `Utilisateur_idUtilisateur`, `StatutDemande_idStatutDemande`),
  INDEX `fk_Demande_Annonce1_idx` (`Annonce_idAnnonce` ASC),
  INDEX `fk_Demande_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Demande_StatutDemande1_idx` (`StatutDemande_idStatutDemande` ASC),
  CONSTRAINT `fk_Demande_Annonce1`
    FOREIGN KEY (`Annonce_idAnnonce`)
    REFERENCES  `Annonce` (`idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demande_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES  `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demande_StatutDemande1`
    FOREIGN KEY (`StatutDemande_idStatutDemande`)
    REFERENCES  `StatutDemande` (`idStatutDemande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `Annonce_has_Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Annonce_has_Utilisateur` (
  `Annonce_idAnnonce` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`Annonce_idAnnonce`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Annonce_has_Utilisateur_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Annonce_has_Utilisateur_Annonce1_idx` (`Annonce_idAnnonce` ASC),
  CONSTRAINT `fk_Annonce_has_Utilisateur_Annonce1`
    FOREIGN KEY (`Annonce_idAnnonce`)
    REFERENCES  `Annonce` (`idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES  `User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
